coverage:
  status:
    project:
      default:
        threshold: 1%
    patch:
      default:
        threshold: 1%

comment:
  layout: 'condensed_header, condensed_files, condensed_footer'
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes
  after_n_builds: 1 # Only expect 1 coverage report (from Node 20 job)

github_checks:
  annotations: true
