coverage:
  status:
    project:
      default:
        threshold: 1%
    patch:
      default:
        threshold: 1%

comment:
  layout: 'condensed_header, condensed_files, condensed_footer'
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes
  after_n_builds: 3 # Expect test results from both matrix jobs + coverage from Node 20

github_checks:
  annotations: true
