coverage:
  status:
    project:
      default:
        threshold: 1%
    patch:
      default:
        threshold: 1%

comment:
  layout: 'condensed_header, condensed_files, condensed_footer'
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes
  after_n_builds: 1 # Only Node 20 job uploads coverage and test results

github_checks:
  annotations: true
