name: Stale Issue Management

on:
  schedule:
    - cron: '0 12 * * *' # Daily at noon UTC
  workflow_dispatch: # Allow manual trigger

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
          # Stale issue configuration
          stale-issue-message: |
            This issue has been automatically marked as stale because it has not had recent activity. 
            
            If this is still a problem, please:
            - Add more details about your setup
            - Confirm you're using the latest version
            - Test with minimal modules to isolate the issue
            
            The issue will be closed if no further activity occurs. Thank you for your contributions!
          stale-issue-label: 'stale'
          days-before-stale: 120
          days-before-close: 28
          
          # Stale PR configuration  
          stale-pr-message: |
            This pull request has been automatically marked as stale because it has not had recent activity.
            
            Please:
            - Rebase on the latest main branch
            - Address any requested changes
            - Update tests if needed
            
            The PR will be closed if no further activity occurs. Thank you for your contribution!
          stale-pr-label: 'stale'
          days-before-pr-stale: 90
          days-before-pr-close: 28
          
          # Labels to exempt from stale processing
          exempt-issue-labels: 'bug,enhancement,help-wanted,good-first-issue,bridge-integration,user-experience,migration'
          exempt-pr-labels: 'work-in-progress,blocked'
          
          # Custom configuration
          close-issue-message: |
            This issue was closed because it has been stale for 14 days with no activity.
            
            If this is still relevant, please open a new issue with updated information.
          close-pr-message: |
            This pull request was closed because it has been stale for 14 days with no activity.
            
            If you'd like to continue this work, please open a new PR with the latest changes.
          
          operations-per-run: 50
          remove-stale-when-updated: true
          ascending: true